example:
  property: I AM A PROD PROPERTY OVERRIDE
redis:
  port: 6379
  server: redis
signing:
  key: 345345fsdfsf5345
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/prod?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: '0510'
    validationQuery: SELECT 1
  jpa:
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update